# Generated by Django 4.2 on 2024-04-20 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255)),
                ('order_status', models.CharField(max_length=255)),
                ('order_total', models.FloatField(default=0)),
                ('order_discount', models.FloatField(blank=True, null=True)),
                ('order_tax', models.FloatField(default=0)),
                ('order_shipping', models.FloatField(blank=True, null=True)),
                ('order_grand_total', models.FloatField(default=0)),
                ('is_online', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.TextField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
        ),
    ]
