# Generated by Django 4.2 on 2024-04-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdata',
            name='customer',
            field=models.CharField(max_length=255),
        ),
    ]
