# Generated by Django 4.2 on 2024-04-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_orderdata_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='order_cost',
            field=models.FloatField(default=0),
        ),
    ]
