# Generated by Django 4.2 on 2024-04-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_orderdata_order_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdata',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
