# Generated by Django 4.2 on 2024-04-21 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_orderdata_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='invoice',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
