# Generated by Django 4.2 on 2024-04-21 05:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_orderdata_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdata',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
