# Generated by Django 4.2 on 2024-04-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='shop_name',
            field=models.CharField(default='LLb', max_length=255),
        ),
    ]
